server:
  port: 8080
  mode: dev
mysql:
  username: quanvm
  password: 098poiA@
  host: localhost
  port: 3306
  dbname: golang-learn
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/log/dev_001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis: 
  host: localhost
  port: 6379
  password:
  database: 0
